"""Add vehicle_sightings table via separate model

Revision ID: 25573440985f
Revises: 93e2f5f74458
Create Date: 2025-07-21 22:56:14.565488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25573440985f'
down_revision = '93e2f5f74458'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'vehicle_sightings' in inspector.get_table_names():
        return
    op.create_table('vehicle_sightings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('registration_plate', sa.String(length=15), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('is_dangerous', sa.Boolean(), nullable=True),
        sa.Column('sighted_at', sa.DateTime(), nullable=True),
        sa.Column('address_seen', sa.String(length=255), nullable=False),
        sa.Column('agent_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_sightings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_sightings_registration_plate'), ['registration_plate'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_sightings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_sightings_registration_plate'))

    op.drop_table('vehicle_sightings')
    # ### end Alembic commands ###
