"""Add verification status to user model

Revision ID: 93e2f5f74458
Revises: c135f3c2dd6c
Create Date: 2025-07-19 22:30:13.373855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93e2f5f74458'
down_revision = 'c135f3c2dd6c'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    cols = [c['name'] for c in inspector.get_columns('users')]
    if 'verification_status' not in cols:
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.add_column(sa.Column('verification_status', sa.String(length=20), server_default='pending', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verification_status')

    # ### end Alembic commands ###
