"""Add utr and document columns to user model

Revision ID: c135f3c2dd6c
Revises: 
Create Date: 2025-07-19 17:42:36.278019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c135f3c2dd6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Idempotent adds to support re-running on environments with drift
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # jobs.hourly_rate
    jobs_columns = [col['name'] for col in inspector.get_columns('jobs')]
    if 'hourly_rate' not in jobs_columns:
        with op.batch_alter_table('jobs', schema=None) as batch_op:
            batch_op.add_column(sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True))

    # users columns
    users_columns = [col['name'] for col in inspector.get_columns('users')]
    with op.batch_alter_table('users', schema=None) as batch_op:
        if 'utr_number' not in users_columns:
            batch_op.add_column(sa.Column('utr_number', sa.String(length=50), nullable=True))
        if 'tax_confirmation' not in users_columns:
            batch_op.add_column(sa.Column('tax_confirmation', sa.Boolean(), nullable=True))
        if 'id_document_url' not in users_columns:
            batch_op.add_column(sa.Column('id_document_url', sa.String(length=255), nullable=True))
        if 'sia_document_url' not in users_columns:
            batch_op.add_column(sa.Column('sia_document_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('sia_document_url')
        batch_op.drop_column('id_document_url')
        batch_op.drop_column('tax_confirmation')
        batch_op.drop_column('utr_number')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('hourly_rate')

    # ### end Alembic commands ###
